default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pai
  password: tigers
  host: db

development:
  <<: *default
  database: pai_app_dev

test:
  <<: *default
  database: pai_app_test

production:
  <<: *default
  database: pai_app_prod
  username: pai_app
  password: <%= ENV["PAI_APP_DATABASE_PASSWORD"] %>
